CREATE TABLE [dbo].[ImportMemberTable] (
    [UniqueId]                          INT            IDENTITY (1, 1) NOT NULL,
    [Clients_Identifier_String]         NVARCHAR (100) NULL,
    [Clients_Identifier_Int]            BIGINT         NULL,
    [External_Communications_Reference] NVARCHAR (100) NULL,
    [Title]                             NVARCHAR (10)  NULL,
    [Salutation]                        NVARCHAR (50)  NULL,
    [Email]                             NVARCHAR (255) NULL,
    [GivenName]                         NVARCHAR (100) NULL,
    [MiddleName]                        NVARCHAR (100) NULL,
    [FamilyName]                        NVARCHAR (100) NULL,
    [LanguageCode]                      NVARCHAR (2)   NULL,
    [SiteRef]                           NVARCHAR (25)  NULL,
    [Dob]                               NVARCHAR (20)  NULL,
    [Gender]                            NVARCHAR (10)  NULL,
    [Add1]                              NVARCHAR (255) NULL,
    [Add2]                              NVARCHAR (255) NULL,
    [Street]                            NVARCHAR (255) NULL,
    [City]                              NVARCHAR (255) NULL,
    [County]                            NVARCHAR (255) NULL,
    [Zip]                               NVARCHAR (255) NULL,
    [Country]                           NVARCHAR (255) NULL,
    [Phone_Fixed]                       NVARCHAR (50)  NULL,
    [Phone_Mobile]                      NVARCHAR (50)  NULL,
    [EmailContact]                      NVARCHAR (5)   NULL,
    [PostContact]                       NVARCHAR (5)   NULL,
    [SmsContact]                        NVARCHAR (5)   NULL,
    [PhoneContact]                      NVARCHAR (5)   NULL,
    [CreateDate]                        DATETIME       NULL,
    [LastModified]                      DATETIME       NULL,
    [LastLogin]                         DATETIME       NULL,
    [Signed]                            NVARCHAR (5)   NULL,
    [StaffNo]                           NVARCHAR (20)  NULL,
    [ImportFileName]                    NVARCHAR (200) NULL,
    [Actioned]                          NVARCHAR (10)  NULL,
    [ImportDate]                        DATETIME       NULL,
    [UserID]                            INT            NULL,
    [ProcessedDate]                     DATETIME       NULL,
    [RejectReason]                      NVARCHAR (100) NULL,
    [ErrorCode]                         NVARCHAR (4)   NULL
);

