CREATE TABLE [dbo].[MemberMergeConfig] (
    [MemberMergeConfigId]       INT        IDENTITY (1, 1) NOT NULL,
    [MinPotentialDupLevel]      FLOAT (53) NOT NULL,
    [MinActualDupLevel]         FLOAT (53) NOT NULL,
    [ScoreExactFirstname]       FLOAT (53) NOT NULL,
    [ScorePartialFirstname]     FLOAT (53) NOT NULL,
    [ScoreFirstLetterFirstname] FLOAT (53) NOT NULL,
    [ScoreExactLastname]        FLOAT (53) NOT NULL,
    [ScorePartialLastname]      FLOAT (53) NOT NULL,
    [ScoreDateOfBirth]          FLOAT (53) NOT NULL,
    [ScoreExactHouseNumber]     FLOAT (53) NOT NULL,
    [ScorePartialHouseNumber]   FLOAT (53) NOT NULL,
    [ScoreExactStreet]          FLOAT (53) NOT NULL,
    [ScorePartialStreet]        FLOAT (53) NOT NULL,
    [ScoreExactCity]            FLOAT (53) NOT NULL,
    [ScorePartialCity]          FLOAT (53) NOT NULL,
    [ScoreExactZip]             FLOAT (53) DEFAULT ((0)) NOT NULL,
    [ScorePartialZip]           FLOAT (53) DEFAULT ((0)) NOT NULL,
    PRIMARY KEY CLUSTERED ([MemberMergeConfigId] ASC),
    CHECK ([MinActualDupLevel]>=(0) AND [MinActualDupLevel]<=(100)),
    CHECK ([MinPotentialDupLevel]>=(0) AND [MinPotentialDupLevel]<=(100)),
    CHECK ([ScoreDateOfBirth]>=(0) AND [ScoreDateOfBirth]<=(100)),
    CHECK ([ScoreExactCity]>=(0) AND [ScoreExactCity]<=(100)),
    CHECK ([ScoreExactFirstname]>=(0) AND [ScoreExactFirstname]<=(100)),
    CHECK ([ScoreExactHouseNumber]>=(0) AND [ScoreExactHouseNumber]<=(100)),
    CHECK ([ScoreExactLastname]>=(0) AND [ScoreExactLastname]<=(100)),
    CHECK ([ScoreExactStreet]>=(0) AND [ScoreExactStreet]<=(100)),
    CHECK ([ScoreFirstLetterFirstname]>=(0) AND [ScoreFirstLetterFirstname]<=[ScoreExactFirstname]),
    CHECK ([ScorePartialCity]>=(0) AND [ScorePartialCity]<=[ScoreExactCity]),
    CHECK ([ScorePartialFirstname]>=(0) AND [ScorePartialFirstname]<=[ScoreExactFirstname]),
    CHECK ([ScorePartialHouseNumber]>=(0) AND [ScorePartialHouseNumber]<=[ScoreExactHouseNumber]),
    CHECK ([ScorePartialLastname]>=(0) AND [ScorePartialLastname]<=[ScoreExactLastname]),
    CHECK ([ScorePartialStreet]>=(0) AND [ScorePartialStreet]<=[ScoreExactStreet])
);

