CREATE TABLE [dbo].[MemberImport] (
    [UniqueId]            INT             IDENTITY (1, 1) NOT NULL,
    [SiteRef]             NVARCHAR (30)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [OldMemberId]         VARCHAR (100)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [MemberId]            INT             NULL,
    [DeviceId]            NVARCHAR (20)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [AccountId]           INT             NULL,
    [SalutationType]      NVARCHAR (50)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [GenderType]          NVARCHAR (50)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [TitleType]           NVARCHAR (50)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [FirstName]           NVARCHAR (100)  COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [LastName]            NVARCHAR (100)  COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [AddressType]         NVARCHAR (30)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [AddressStatus]       NVARCHAR (30)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [AddressLine1]        NVARCHAR (255)  COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [AddressLine2]        NVARCHAR (255)  COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [HouseName]           NVARCHAR (80)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [HouseNumber]         NVARCHAR (50)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Street]              NVARCHAR (255)  COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Locality]            NVARCHAR (80)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [City]                NVARCHAR (255)  COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [County]              NVARCHAR (60)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Zip]                 NVARCHAR (50)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Country]             NVARCHAR (20)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [PostBox]             INT             NULL,
    [PostBoxNumber]       NVARCHAR (50)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [DoB]                 NVARCHAR (20)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Email]               NVARCHAR (255)  COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Phone]               NVARCHAR (255)  COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Mobile]              NVARCHAR (255)  COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [EmailStatus]         NVARCHAR (50)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [UserType]            NVARCHAR (80)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [UserSubType]         NVARCHAR (80)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [ContactDetailsType]  NVARCHAR (80)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [LanguageCode]        NVARCHAR (80)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [ContactByEmail]      NVARCHAR (4)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [ContactByMail]       NVARCHAR (4)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [ContactBySms]        NVARCHAR (4)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [ContactByPhone]      NVARCHAR (4)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [MonetaryBalance]     DECIMAL (18, 2) NULL,
    [PointsBalance]       DECIMAL (18, 2) NULL,
    [DeviceStatus]        NVARCHAR (30)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Version]             NVARCHAR (10)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [TurnoverBalance]     DECIMAL (18, 2) NULL,
    [DeviceType]          NVARCHAR (30)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [CommunityId]         NVARCHAR (30)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [OldDeviceId]         NVARCHAR (50)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [TurnoverBalanceTemp] DECIMAL (18, 2) NULL,
    [MpiId]               NVARCHAR (13)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [SocialSecurity]      NVARCHAR (50)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [CoverCard]           NVARCHAR (20)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [ErrorNotes]          NVARCHAR (MAX)  COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [ErrorCode]           NVARCHAR (20)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [ImportTableName]     NVARCHAR (200)  COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Actioned]            NVARCHAR (50)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [ImportDate]          DATETIME        NULL,
    [ProcessedDate]       DATETIME        NULL,
    [Points]              INT             NULL,
    [CardNumber]          NVARCHAR (50)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [CardNumberBoss]      NVARCHAR (50)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [UserId]              INT             NULL,
    CONSTRAINT [PK_MemberImport_ID] PRIMARY KEY CLUSTERED ([UniqueId] ASC)
);

