CREATE TABLE [dbo].[SegHeader] (
    [SegmentId]             INT             IDENTITY (1, 1) NOT NULL,
    [CampaignId]            INT             DEFAULT ((0)) NOT NULL,
    [Name]                  VARCHAR (50)    NULL,
    [Description]           VARCHAR (500)   NULL,
    [Priority]              INT             NULL,
    [Selected]              BIT             NULL,
    [MaxOutput]             INT             NULL,
    [OutputType]            TINYINT         NULL,
    [OutputMsg]             VARCHAR (MAX)   NULL,
    [OutputCode]            VARCHAR (20)    NULL,
    [TemplateId]            INT             NULL,
    [Count]                 INT             NULL,
    [CountDate]             SMALLDATETIME   NULL,
    [RunCount]              INT             NULL,
    [RunDate]               DATETIME        NULL,
    [LastUpdated]           DATETIME        NOT NULL,
    [UpdatedBy]             INT             NOT NULL,
    [Issued]                INT             NULL,
    [NoResponses]           INT             NULL,
    [FixedCosts]            DECIMAL (18, 2) NULL,
    [VariableCosts]         DECIMAL (18, 2) NULL,
    [HandlingCosts]         DECIMAL (18, 2) NULL,
    [TransportCosts]        DECIMAL (18, 2) NULL,
    [GeneratedIncome]       DECIMAL (18, 2) NULL,
    [MaxVouchers]           INT             CONSTRAINT [DF_SegHeader_MaxVouchers] DEFAULT ((0)) NULL,
    [Email]                 VARCHAR (50)    NULL,
    [AddressSelectionId]    SMALLINT        NULL,
    [DataMatrixRNN]         VARCHAR (50)    NULL,
    [SegmentListId]         INT             NULL,
    [SelectionSQL]          NVARCHAR (MAX)  NULL,
    [SelectionSQLValidated] INT             NULL,
    CONSTRAINT [PK_SegHeader] PRIMARY KEY CLUSTERED ([SegmentId] ASC) WITH (FILLFACTOR = 100),
    CONSTRAINT [FK_SegHeader_Campaign] FOREIGN KEY ([CampaignId]) REFERENCES [dbo].[Campaign] ([CampaignId])
);

