CREATE TABLE [SSISHelper].[OrderFulfillment] (
    [ID]                    INT            IDENTITY (1, 1) NOT NULL,
    [Job Number]            NVARCHAR (10)  NULL,
    [Job Description]       NVARCHAR (25)  NULL,
    [Program]               NVARCHAR (25)  NULL,
    [DC]                    NVARCHAR (25)  NULL,
    [Sales Rep Code]        NVARCHAR (10)  NULL,
    [Sales First Name]      NVARCHAR (50)  NULL,
    [Sales Last Name]       NVARCHAR (50)  NULL,
    [Client Order #]        NVARCHAR (50)  NULL,
    [Order Number]          NVARCHAR (50)  NULL,
    [Original Order Number] NVARCHAR (50)  NULL,
    [Cost Center]           NVARCHAR (10)  NULL,
    [Customer Number]       NVARCHAR (30)  NULL,
    [Customer Company]      NVARCHAR (100) NULL,
    [Order Date]            DATETIME       NULL,
    [Ship Date]             DATETIME       NULL,
    [Ship to Company]       NVARCHAR (100) NULL,
    [Ship to First Name]    NVARCHAR (50)  NULL,
    [Ship to Last Name]     NVARCHAR (50)  NULL,
    [Ship to Address 1]     NVARCHAR (100) NULL,
    [Ship to Address 2]     NVARCHAR (100) NULL,
    [Ship to Address 3]     NVARCHAR (100) NULL,
    [Ship to City]          NVARCHAR (50)  NULL,
    [Ship to State]         NVARCHAR (10)  NULL,
    [Ship to Zip]           NVARCHAR (10)  NULL,
    [Ship to Country]       NVARCHAR (20)  NULL,
    [Ship to Email]         NVARCHAR (255) NULL,
    [Bill to Company]       NVARCHAR (100) NULL,
    [Bill to Name]          NVARCHAR (100) NULL,
    [Bill to Address 1]     NVARCHAR (100) NULL,
    [Bill to Address 2]     NVARCHAR (100) NULL,
    [Bill to Address 3]     NVARCHAR (100) NULL,
    [Bill to City]          NVARCHAR (50)  NULL,
    [Bill to State]         NVARCHAR (10)  NULL,
    [Bill to Zip]           NVARCHAR (10)  NULL,
    [Bill to Country]       NVARCHAR (20)  NULL,
    [Bill to Email]         NVARCHAR (100) NULL,
    [Stock Number]          NVARCHAR (25)  NULL,
    [Stock Description]     NVARCHAR (200) NULL,
    [Unit Price]            FLOAT (53)     NULL,
    [Order Qty]             FLOAT (53)     NULL,
    [Ship Qty]              FLOAT (53)     NULL,
    [Order Status]          NVARCHAR (10)  NULL,
    [Item Status]           NVARCHAR (10)  NULL,
    [Client Batch#]         NVARCHAR (50)  NULL,
    [Order Classification]  NVARCHAR (20)  NULL,
    [Entity Code]           NVARCHAR (20)  NULL,
    [Reserve Code]          NVARCHAR (50)  NULL,
    [Tracking Number(s)]    NVARCHAR (50)  NULL,
    [ImportFileName]        NVARCHAR (100) NULL,
    [ImportDate]            DATETIME       NULL,
    [Status]                NVARCHAR (1)   NULL
);

