
-- =============================================
-- AUTHOR:		WEI LIU
-- CREATE DATE: 01/11/2022
-- DESCRIPTION:	VALIDATE RECEIPT BASE ON CONDITIONS
-- RETURN CODE:
	-- 1 = ALREADY APPROVED
	-- 0 = NOT APPROVED

-- ===========================================
	--DECLARE @Code INT
	--EXEC [API_RECEIPTVALIDATOR] 1, 'Cgt9VXpYc',  @Code OUTPUT
	--SELECT @Code
-- =============================================
CREATE PROCEDURE [dbo].[Api_ReceiptValidator] (@ClientId INT, @Reference NVARCHAR(100),  @Code bit OUTPUT)
AS
BEGIN

	SET NOCOUNT ON;
	--DECLARE @CLIENTID INT, @REFERENCE NVARCHAR(100), @CODE INT
	DECLARE @TRXWITHREFERENCE TABLE (TRXID INT)
	DECLARE @APPROVALTRXIDS TABLE (TRXID INT)
	DECLARE @APPROVALGROUPTRXIDS TABLE (TRXID INT)
	SET @CLIENTID = 1

	-- GET ALL TRANSACTION THAT ARE LINKED TO THE RECEIPT ID PASSED
	INSERT INTO @TRXWITHREFERENCE (TRXID)
	SELECT TRXID FROM TRXHEADER TH
	JOIN [SITE] S ON TH.SITEID = S.SITEID
	JOIN TRXTYPE TT ON TT.TRXTYPEID = TH.TRXTYPEID
	WHERE REFERENCE = @REFERENCE AND S.CLIENTID = @CLIENTID 
	AND TT.[NAME] IN ('RECEIPT', 'INVALIDRECEIPT')

	-- CHECK IF ANY APPROVED TRANSACTION EXISTS WITH THE TRX IDS GIVEN
	INSERT INTO @APPROVALTRXIDS (TRXID)
	SELECT DISTINCT THE.TRXID FROM TRXHEADEREXTENSIONDATA THE
	WHERE (THE.PROPERTYNAME = 'APPROVAL' AND (THE.PROPERTYVALUE = 'APPROVED' OR THE.PROPERTYVALUE = 'REJECTED')) 
	AND TRXID IN (SELECT TRXID FROM @TRXWITHREFERENCE) 

	-- RETURN 1 IF FOUND IN @APPROVALTRXIDS
	IF EXISTS(SELECT TOP 1 * FROM @APPROVALTRXIDS)
	BEGIN
		SET @Code =  1
	END
	ELSE
	BEGIN
		-- GET ALL GROUPED APPROVED TRANSACTIONS
		INSERT INTO @APPROVALGROUPTRXIDS(TRXID)
		SELECT DISTINCT TH.TRXID  FROM TRXHEADER TH JOIN TRXHEADEREXTENSIONDATA THED
		ON TH.INITIALTRANSACTION = THED.TRXID
		WHERE THED.PROPERTYNAME = 'APPROVAL'

		-- CHECK IF ANY GROUPED APPROVED TRANSACTION EXISTS WITH THE TRX IDS GIVEN
		IF EXISTS(SELECT TOP 1 * FROM @APPROVALGROUPTRXIDS WHERE TRXID IN (SELECT TRXID FROM @TRXWITHREFERENCE))
		BEGIN
			SET @Code =  1
		END
		ELSE
		BEGIN
			SET @Code =  0
		END
	END

	RETURN @Code
END
